### ISSUE TITLE
Orion on Ubuntu 18.04

### ISSUE THREAD

**Issue by tmontanaro** [telefonicaid/fiware-orion#3228]
Hello, I'm again here.
After installing Orion on Ubuntu 14.04 (through the instructions I reported here [Stackoverflow post](https://stackoverflow.com/questions/28463012/fiware-orion-context-broker-on-ubuntu/47791029#47791029)
Now I'm trying to install it on Ubuntu 18.04!
As expected it is becoming, again, a nightmare.
The problems born from the dependency on mongo-cxx-driver.

I tried with 2 different alternatives:
1. Follow the exact instructions used with Ubuntu 14.04   
    In this case I encountered a problem in installing `mongo-cxx-driver` v. 1.1.2.
    While compiling I get the following error
    ```
    src/mongo/util/assert_util.h:231:28: error: nonnull argument 'this' compared to NULL [-Werror=nonnull-compare]
         if (MONGO_unlikely(!(expr))) {      \
                            ^~~~~~~
    ```
    Considering that the driver is currently at the 3.3.3 version, it is difficult to obtain support for a so old version. So, I decided to go to the next point
2. Follow the exact instructions used with Ubuntu 14.04 but by using the 3.3.3 version of mongo-cxx-driver.
    In this case, everything seems to work until the "linker" step arrives.
    If fact, even though the Orion compiler arrives at 100%, then it cannot link, and it returns the following error:
    ```
    /usr/bin/x86_64-linux-gnu-ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmongoclient.a(ssl_manager.o): undefined reference to symbol 'X509_free@@OPENSSL_1_1_0'
    //usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: error adding symbols: DSO missing from command line collect2: error: ld returned 1 exit status
    src/app/contextBroker/CMakeFiles/contextBroker.dir/build.make:143: recipe for target 'src/app/contextBroker/contextBroker' failed
    ```   

Does anyone know what can I do to solve this problem?
Thank you in advance

**Comment by fgalan** [comment]
At the present moment Orion depends on legacy-1.1.2 (see https://fiware-orion.readthedocs.io/en/master/admin/build_source/index.html). It may happen that trying to build it in modern OS fails. In that case, note that the official distribution for Orion is, by the time being, CentOS/RHEL 7.

At the present moment Orion is not going to work with driver version 3.3.3. There is an issue about driver migration (see https://github.com/telefonicaid/fiware-orion/issues/3132) and even a PR with some early work (see https://github.com/telefonicaid/fiware-orion/pull/3139) but not yet finalized (and it would take some time... it is a complex task)

CC: @saurabhjangir

**Comment by fgalan** [comment]
(I'd suggest to close this issue, as it is already covered by #3132, from my point of view)
